Use facterdb with db_spec file
With OS facts set the following error occured:

```
NoMethodError:
     #   undefined method `downcase' for nil:NilClass
     #   ./vendor/bundle/ruby/3.2.0/gems/puppet-8.3.1/lib/puppet/provider/service/init.rb:25:in `block in <top (required)>'
```

since the service provider could not be determined correctly.